/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookieIndexRouteImport } from './routes/cookie/index'
import { Route as BoardIndexRouteImport } from './routes/board/index'
import { Route as StrategyCookietierRouteImport } from './routes/strategy/cookietier'
import { Route as NewUserGuideListRouteImport } from './routes/newUserGuide/list'
import { Route as CookieArticleIdRouteImport } from './routes/cookie/$articleId'
import { Route as BoardWriteRouteImport } from './routes/board/write'
import { Route as BoardArticleIdRouteImport } from './routes/board/$articleId'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as NewUserGuideGuidesRecommendCookieRouteImport } from './routes/newUserGuide/guides/recommendCookie'
import { Route as NewUserGuideGuidesGetCoinRouteImport } from './routes/newUserGuide/guides/getCoin'
import { Route as NewUserGuideGuidesAboutLegendaryRouteImport } from './routes/newUserGuide/guides/aboutLegendary'
import { Route as NewUserGuideGuidesAboutGemRouteImport } from './routes/newUserGuide/guides/aboutGem'
import { Route as NewUserGuideGuidesAboutCrystalRouteImport } from './routes/newUserGuide/guides/aboutCrystal'
import { Route as NewUserGuideGuidesAboutBoxRouteImport } from './routes/newUserGuide/guides/aboutBox'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieIndexRoute = CookieIndexRouteImport.update({
  id: '/cookie/',
  path: '/cookie/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyCookietierRoute = StrategyCookietierRouteImport.update({
  id: '/strategy/cookietier',
  path: '/strategy/cookietier',
  getParentRoute: () => rootRouteImport,
} as any)
const NewUserGuideListRoute = NewUserGuideListRouteImport.update({
  id: '/newUserGuide/list',
  path: '/newUserGuide/list',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieArticleIdRoute = CookieArticleIdRouteImport.update({
  id: '/cookie/$articleId',
  path: '/cookie/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardWriteRoute = BoardWriteRouteImport.update({
  id: '/board/write',
  path: '/board/write',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardArticleIdRoute = BoardArticleIdRouteImport.update({
  id: '/board/$articleId',
  path: '/board/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewUserGuideGuidesRecommendCookieRoute =
  NewUserGuideGuidesRecommendCookieRouteImport.update({
    id: '/newUserGuide/guides/recommendCookie',
    path: '/newUserGuide/guides/recommendCookie',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewUserGuideGuidesGetCoinRoute =
  NewUserGuideGuidesGetCoinRouteImport.update({
    id: '/newUserGuide/guides/getCoin',
    path: '/newUserGuide/guides/getCoin',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewUserGuideGuidesAboutLegendaryRoute =
  NewUserGuideGuidesAboutLegendaryRouteImport.update({
    id: '/newUserGuide/guides/aboutLegendary',
    path: '/newUserGuide/guides/aboutLegendary',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewUserGuideGuidesAboutGemRoute =
  NewUserGuideGuidesAboutGemRouteImport.update({
    id: '/newUserGuide/guides/aboutGem',
    path: '/newUserGuide/guides/aboutGem',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewUserGuideGuidesAboutCrystalRoute =
  NewUserGuideGuidesAboutCrystalRouteImport.update({
    id: '/newUserGuide/guides/aboutCrystal',
    path: '/newUserGuide/guides/aboutCrystal',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewUserGuideGuidesAboutBoxRoute =
  NewUserGuideGuidesAboutBoxRouteImport.update({
    id: '/newUserGuide/guides/aboutBox',
    path: '/newUserGuide/guides/aboutBox',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/board/$articleId': typeof BoardArticleIdRoute
  '/board/write': typeof BoardWriteRoute
  '/cookie/$articleId': typeof CookieArticleIdRoute
  '/newUserGuide/list': typeof NewUserGuideListRoute
  '/strategy/cookietier': typeof StrategyCookietierRoute
  '/board': typeof BoardIndexRoute
  '/cookie': typeof CookieIndexRoute
  '/newUserGuide/guides/aboutBox': typeof NewUserGuideGuidesAboutBoxRoute
  '/newUserGuide/guides/aboutCrystal': typeof NewUserGuideGuidesAboutCrystalRoute
  '/newUserGuide/guides/aboutGem': typeof NewUserGuideGuidesAboutGemRoute
  '/newUserGuide/guides/aboutLegendary': typeof NewUserGuideGuidesAboutLegendaryRoute
  '/newUserGuide/guides/getCoin': typeof NewUserGuideGuidesGetCoinRoute
  '/newUserGuide/guides/recommendCookie': typeof NewUserGuideGuidesRecommendCookieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/board/$articleId': typeof BoardArticleIdRoute
  '/board/write': typeof BoardWriteRoute
  '/cookie/$articleId': typeof CookieArticleIdRoute
  '/newUserGuide/list': typeof NewUserGuideListRoute
  '/strategy/cookietier': typeof StrategyCookietierRoute
  '/board': typeof BoardIndexRoute
  '/cookie': typeof CookieIndexRoute
  '/newUserGuide/guides/aboutBox': typeof NewUserGuideGuidesAboutBoxRoute
  '/newUserGuide/guides/aboutCrystal': typeof NewUserGuideGuidesAboutCrystalRoute
  '/newUserGuide/guides/aboutGem': typeof NewUserGuideGuidesAboutGemRoute
  '/newUserGuide/guides/aboutLegendary': typeof NewUserGuideGuidesAboutLegendaryRoute
  '/newUserGuide/guides/getCoin': typeof NewUserGuideGuidesGetCoinRoute
  '/newUserGuide/guides/recommendCookie': typeof NewUserGuideGuidesRecommendCookieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/board/$articleId': typeof BoardArticleIdRoute
  '/board/write': typeof BoardWriteRoute
  '/cookie/$articleId': typeof CookieArticleIdRoute
  '/newUserGuide/list': typeof NewUserGuideListRoute
  '/strategy/cookietier': typeof StrategyCookietierRoute
  '/board/': typeof BoardIndexRoute
  '/cookie/': typeof CookieIndexRoute
  '/newUserGuide/guides/aboutBox': typeof NewUserGuideGuidesAboutBoxRoute
  '/newUserGuide/guides/aboutCrystal': typeof NewUserGuideGuidesAboutCrystalRoute
  '/newUserGuide/guides/aboutGem': typeof NewUserGuideGuidesAboutGemRoute
  '/newUserGuide/guides/aboutLegendary': typeof NewUserGuideGuidesAboutLegendaryRoute
  '/newUserGuide/guides/getCoin': typeof NewUserGuideGuidesGetCoinRoute
  '/newUserGuide/guides/recommendCookie': typeof NewUserGuideGuidesRecommendCookieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth/login'
    | '/auth/signup'
    | '/board/$articleId'
    | '/board/write'
    | '/cookie/$articleId'
    | '/newUserGuide/list'
    | '/strategy/cookietier'
    | '/board'
    | '/cookie'
    | '/newUserGuide/guides/aboutBox'
    | '/newUserGuide/guides/aboutCrystal'
    | '/newUserGuide/guides/aboutGem'
    | '/newUserGuide/guides/aboutLegendary'
    | '/newUserGuide/guides/getCoin'
    | '/newUserGuide/guides/recommendCookie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/login'
    | '/auth/signup'
    | '/board/$articleId'
    | '/board/write'
    | '/cookie/$articleId'
    | '/newUserGuide/list'
    | '/strategy/cookietier'
    | '/board'
    | '/cookie'
    | '/newUserGuide/guides/aboutBox'
    | '/newUserGuide/guides/aboutCrystal'
    | '/newUserGuide/guides/aboutGem'
    | '/newUserGuide/guides/aboutLegendary'
    | '/newUserGuide/guides/getCoin'
    | '/newUserGuide/guides/recommendCookie'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth/login'
    | '/auth/signup'
    | '/board/$articleId'
    | '/board/write'
    | '/cookie/$articleId'
    | '/newUserGuide/list'
    | '/strategy/cookietier'
    | '/board/'
    | '/cookie/'
    | '/newUserGuide/guides/aboutBox'
    | '/newUserGuide/guides/aboutCrystal'
    | '/newUserGuide/guides/aboutGem'
    | '/newUserGuide/guides/aboutLegendary'
    | '/newUserGuide/guides/getCoin'
    | '/newUserGuide/guides/recommendCookie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BoardArticleIdRoute: typeof BoardArticleIdRoute
  BoardWriteRoute: typeof BoardWriteRoute
  CookieArticleIdRoute: typeof CookieArticleIdRoute
  NewUserGuideListRoute: typeof NewUserGuideListRoute
  StrategyCookietierRoute: typeof StrategyCookietierRoute
  BoardIndexRoute: typeof BoardIndexRoute
  CookieIndexRoute: typeof CookieIndexRoute
  NewUserGuideGuidesAboutBoxRoute: typeof NewUserGuideGuidesAboutBoxRoute
  NewUserGuideGuidesAboutCrystalRoute: typeof NewUserGuideGuidesAboutCrystalRoute
  NewUserGuideGuidesAboutGemRoute: typeof NewUserGuideGuidesAboutGemRoute
  NewUserGuideGuidesAboutLegendaryRoute: typeof NewUserGuideGuidesAboutLegendaryRoute
  NewUserGuideGuidesGetCoinRoute: typeof NewUserGuideGuidesGetCoinRoute
  NewUserGuideGuidesRecommendCookieRoute: typeof NewUserGuideGuidesRecommendCookieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie/': {
      id: '/cookie/'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/': {
      id: '/board/'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy/cookietier': {
      id: '/strategy/cookietier'
      path: '/strategy/cookietier'
      fullPath: '/strategy/cookietier'
      preLoaderRoute: typeof StrategyCookietierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newUserGuide/list': {
      id: '/newUserGuide/list'
      path: '/newUserGuide/list'
      fullPath: '/newUserGuide/list'
      preLoaderRoute: typeof NewUserGuideListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie/$articleId': {
      id: '/cookie/$articleId'
      path: '/cookie/$articleId'
      fullPath: '/cookie/$articleId'
      preLoaderRoute: typeof CookieArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/write': {
      id: '/board/write'
      path: '/board/write'
      fullPath: '/board/write'
      preLoaderRoute: typeof BoardWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$articleId': {
      id: '/board/$articleId'
      path: '/board/$articleId'
      fullPath: '/board/$articleId'
      preLoaderRoute: typeof BoardArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newUserGuide/guides/recommendCookie': {
      id: '/newUserGuide/guides/recommendCookie'
      path: '/newUserGuide/guides/recommendCookie'
      fullPath: '/newUserGuide/guides/recommendCookie'
      preLoaderRoute: typeof NewUserGuideGuidesRecommendCookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newUserGuide/guides/getCoin': {
      id: '/newUserGuide/guides/getCoin'
      path: '/newUserGuide/guides/getCoin'
      fullPath: '/newUserGuide/guides/getCoin'
      preLoaderRoute: typeof NewUserGuideGuidesGetCoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newUserGuide/guides/aboutLegendary': {
      id: '/newUserGuide/guides/aboutLegendary'
      path: '/newUserGuide/guides/aboutLegendary'
      fullPath: '/newUserGuide/guides/aboutLegendary'
      preLoaderRoute: typeof NewUserGuideGuidesAboutLegendaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newUserGuide/guides/aboutGem': {
      id: '/newUserGuide/guides/aboutGem'
      path: '/newUserGuide/guides/aboutGem'
      fullPath: '/newUserGuide/guides/aboutGem'
      preLoaderRoute: typeof NewUserGuideGuidesAboutGemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newUserGuide/guides/aboutCrystal': {
      id: '/newUserGuide/guides/aboutCrystal'
      path: '/newUserGuide/guides/aboutCrystal'
      fullPath: '/newUserGuide/guides/aboutCrystal'
      preLoaderRoute: typeof NewUserGuideGuidesAboutCrystalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newUserGuide/guides/aboutBox': {
      id: '/newUserGuide/guides/aboutBox'
      path: '/newUserGuide/guides/aboutBox'
      fullPath: '/newUserGuide/guides/aboutBox'
      preLoaderRoute: typeof NewUserGuideGuidesAboutBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  BoardArticleIdRoute: BoardArticleIdRoute,
  BoardWriteRoute: BoardWriteRoute,
  CookieArticleIdRoute: CookieArticleIdRoute,
  NewUserGuideListRoute: NewUserGuideListRoute,
  StrategyCookietierRoute: StrategyCookietierRoute,
  BoardIndexRoute: BoardIndexRoute,
  CookieIndexRoute: CookieIndexRoute,
  NewUserGuideGuidesAboutBoxRoute: NewUserGuideGuidesAboutBoxRoute,
  NewUserGuideGuidesAboutCrystalRoute: NewUserGuideGuidesAboutCrystalRoute,
  NewUserGuideGuidesAboutGemRoute: NewUserGuideGuidesAboutGemRoute,
  NewUserGuideGuidesAboutLegendaryRoute: NewUserGuideGuidesAboutLegendaryRoute,
  NewUserGuideGuidesGetCoinRoute: NewUserGuideGuidesGetCoinRoute,
  NewUserGuideGuidesRecommendCookieRoute:
    NewUserGuideGuidesRecommendCookieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
