/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagementIndexRouteImport } from './routes/management/index'
import { Route as CookieIndexRouteImport } from './routes/cookie/index'
import { Route as BoardIndexRouteImport } from './routes/board/index'
import { Route as StrategyCookietierRouteImport } from './routes/strategy/cookietier'
import { Route as NewUserGuideListRouteImport } from './routes/newUserGuide/list'
import { Route as ManagementTreasureRouteImport } from './routes/management/treasure'
import { Route as ManagementPetManRouteImport } from './routes/management/petMan'
import { Route as ManagementInquiryRouteImport } from './routes/management/inquiry'
import { Route as ManagementCookieManRouteImport } from './routes/management/cookieMan'
import { Route as ManagementBoardRouteImport } from './routes/management/board'
import { Route as ManagementBannerRouteImport } from './routes/management/banner'
import { Route as CookieArticleIdRouteImport } from './routes/cookie/$articleId'
import { Route as BoardWriteRouteImport } from './routes/board/write'
import { Route as BoardArticleIdRouteImport } from './routes/board/$articleId'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as NewUserGuideGuidesRecommendCookieRouteImport } from './routes/newUserGuide/guides/recommendCookie'
import { Route as NewUserGuideGuidesGetCoinRouteImport } from './routes/newUserGuide/guides/getCoin'
import { Route as NewUserGuideGuidesAboutLegendaryRouteImport } from './routes/newUserGuide/guides/aboutLegendary'
import { Route as NewUserGuideGuidesAboutGemRouteImport } from './routes/newUserGuide/guides/aboutGem'
import { Route as NewUserGuideGuidesAboutCrystalRouteImport } from './routes/newUserGuide/guides/aboutCrystal'
import { Route as NewUserGuideGuidesAboutBoxRouteImport } from './routes/newUserGuide/guides/aboutBox'
import { Route as ManagementPetAddRouteImport } from './routes/management/pet/add'
import { Route as ManagementCookieAddRouteImport } from './routes/management/cookie/add'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementIndexRoute = ManagementIndexRouteImport.update({
  id: '/management/',
  path: '/management/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieIndexRoute = CookieIndexRouteImport.update({
  id: '/cookie/',
  path: '/cookie/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyCookietierRoute = StrategyCookietierRouteImport.update({
  id: '/strategy/cookietier',
  path: '/strategy/cookietier',
  getParentRoute: () => rootRouteImport,
} as any)
const NewUserGuideListRoute = NewUserGuideListRouteImport.update({
  id: '/newUserGuide/list',
  path: '/newUserGuide/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementTreasureRoute = ManagementTreasureRouteImport.update({
  id: '/management/treasure',
  path: '/management/treasure',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementPetManRoute = ManagementPetManRouteImport.update({
  id: '/management/petMan',
  path: '/management/petMan',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementInquiryRoute = ManagementInquiryRouteImport.update({
  id: '/management/inquiry',
  path: '/management/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementCookieManRoute = ManagementCookieManRouteImport.update({
  id: '/management/cookieMan',
  path: '/management/cookieMan',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementBoardRoute = ManagementBoardRouteImport.update({
  id: '/management/board',
  path: '/management/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementBannerRoute = ManagementBannerRouteImport.update({
  id: '/management/banner',
  path: '/management/banner',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieArticleIdRoute = CookieArticleIdRouteImport.update({
  id: '/cookie/$articleId',
  path: '/cookie/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardWriteRoute = BoardWriteRouteImport.update({
  id: '/board/write',
  path: '/board/write',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardArticleIdRoute = BoardArticleIdRouteImport.update({
  id: '/board/$articleId',
  path: '/board/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewUserGuideGuidesRecommendCookieRoute =
  NewUserGuideGuidesRecommendCookieRouteImport.update({
    id: '/newUserGuide/guides/recommendCookie',
    path: '/newUserGuide/guides/recommendCookie',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewUserGuideGuidesGetCoinRoute =
  NewUserGuideGuidesGetCoinRouteImport.update({
    id: '/newUserGuide/guides/getCoin',
    path: '/newUserGuide/guides/getCoin',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewUserGuideGuidesAboutLegendaryRoute =
  NewUserGuideGuidesAboutLegendaryRouteImport.update({
    id: '/newUserGuide/guides/aboutLegendary',
    path: '/newUserGuide/guides/aboutLegendary',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewUserGuideGuidesAboutGemRoute =
  NewUserGuideGuidesAboutGemRouteImport.update({
    id: '/newUserGuide/guides/aboutGem',
    path: '/newUserGuide/guides/aboutGem',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewUserGuideGuidesAboutCrystalRoute =
  NewUserGuideGuidesAboutCrystalRouteImport.update({
    id: '/newUserGuide/guides/aboutCrystal',
    path: '/newUserGuide/guides/aboutCrystal',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewUserGuideGuidesAboutBoxRoute =
  NewUserGuideGuidesAboutBoxRouteImport.update({
    id: '/newUserGuide/guides/aboutBox',
    path: '/newUserGuide/guides/aboutBox',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManagementPetAddRoute = ManagementPetAddRouteImport.update({
  id: '/management/pet/add',
  path: '/management/pet/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementCookieAddRoute = ManagementCookieAddRouteImport.update({
  id: '/management/cookie/add',
  path: '/management/cookie/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/board/$articleId': typeof BoardArticleIdRoute
  '/board/write': typeof BoardWriteRoute
  '/cookie/$articleId': typeof CookieArticleIdRoute
  '/management/banner': typeof ManagementBannerRoute
  '/management/board': typeof ManagementBoardRoute
  '/management/cookieMan': typeof ManagementCookieManRoute
  '/management/inquiry': typeof ManagementInquiryRoute
  '/management/petMan': typeof ManagementPetManRoute
  '/management/treasure': typeof ManagementTreasureRoute
  '/newUserGuide/list': typeof NewUserGuideListRoute
  '/strategy/cookietier': typeof StrategyCookietierRoute
  '/board': typeof BoardIndexRoute
  '/cookie': typeof CookieIndexRoute
  '/management': typeof ManagementIndexRoute
  '/management/cookie/add': typeof ManagementCookieAddRoute
  '/management/pet/add': typeof ManagementPetAddRoute
  '/newUserGuide/guides/aboutBox': typeof NewUserGuideGuidesAboutBoxRoute
  '/newUserGuide/guides/aboutCrystal': typeof NewUserGuideGuidesAboutCrystalRoute
  '/newUserGuide/guides/aboutGem': typeof NewUserGuideGuidesAboutGemRoute
  '/newUserGuide/guides/aboutLegendary': typeof NewUserGuideGuidesAboutLegendaryRoute
  '/newUserGuide/guides/getCoin': typeof NewUserGuideGuidesGetCoinRoute
  '/newUserGuide/guides/recommendCookie': typeof NewUserGuideGuidesRecommendCookieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/board/$articleId': typeof BoardArticleIdRoute
  '/board/write': typeof BoardWriteRoute
  '/cookie/$articleId': typeof CookieArticleIdRoute
  '/management/banner': typeof ManagementBannerRoute
  '/management/board': typeof ManagementBoardRoute
  '/management/cookieMan': typeof ManagementCookieManRoute
  '/management/inquiry': typeof ManagementInquiryRoute
  '/management/petMan': typeof ManagementPetManRoute
  '/management/treasure': typeof ManagementTreasureRoute
  '/newUserGuide/list': typeof NewUserGuideListRoute
  '/strategy/cookietier': typeof StrategyCookietierRoute
  '/board': typeof BoardIndexRoute
  '/cookie': typeof CookieIndexRoute
  '/management': typeof ManagementIndexRoute
  '/management/cookie/add': typeof ManagementCookieAddRoute
  '/management/pet/add': typeof ManagementPetAddRoute
  '/newUserGuide/guides/aboutBox': typeof NewUserGuideGuidesAboutBoxRoute
  '/newUserGuide/guides/aboutCrystal': typeof NewUserGuideGuidesAboutCrystalRoute
  '/newUserGuide/guides/aboutGem': typeof NewUserGuideGuidesAboutGemRoute
  '/newUserGuide/guides/aboutLegendary': typeof NewUserGuideGuidesAboutLegendaryRoute
  '/newUserGuide/guides/getCoin': typeof NewUserGuideGuidesGetCoinRoute
  '/newUserGuide/guides/recommendCookie': typeof NewUserGuideGuidesRecommendCookieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/board/$articleId': typeof BoardArticleIdRoute
  '/board/write': typeof BoardWriteRoute
  '/cookie/$articleId': typeof CookieArticleIdRoute
  '/management/banner': typeof ManagementBannerRoute
  '/management/board': typeof ManagementBoardRoute
  '/management/cookieMan': typeof ManagementCookieManRoute
  '/management/inquiry': typeof ManagementInquiryRoute
  '/management/petMan': typeof ManagementPetManRoute
  '/management/treasure': typeof ManagementTreasureRoute
  '/newUserGuide/list': typeof NewUserGuideListRoute
  '/strategy/cookietier': typeof StrategyCookietierRoute
  '/board/': typeof BoardIndexRoute
  '/cookie/': typeof CookieIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/management/cookie/add': typeof ManagementCookieAddRoute
  '/management/pet/add': typeof ManagementPetAddRoute
  '/newUserGuide/guides/aboutBox': typeof NewUserGuideGuidesAboutBoxRoute
  '/newUserGuide/guides/aboutCrystal': typeof NewUserGuideGuidesAboutCrystalRoute
  '/newUserGuide/guides/aboutGem': typeof NewUserGuideGuidesAboutGemRoute
  '/newUserGuide/guides/aboutLegendary': typeof NewUserGuideGuidesAboutLegendaryRoute
  '/newUserGuide/guides/getCoin': typeof NewUserGuideGuidesGetCoinRoute
  '/newUserGuide/guides/recommendCookie': typeof NewUserGuideGuidesRecommendCookieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth/login'
    | '/auth/signup'
    | '/board/$articleId'
    | '/board/write'
    | '/cookie/$articleId'
    | '/management/banner'
    | '/management/board'
    | '/management/cookieMan'
    | '/management/inquiry'
    | '/management/petMan'
    | '/management/treasure'
    | '/newUserGuide/list'
    | '/strategy/cookietier'
    | '/board'
    | '/cookie'
    | '/management'
    | '/management/cookie/add'
    | '/management/pet/add'
    | '/newUserGuide/guides/aboutBox'
    | '/newUserGuide/guides/aboutCrystal'
    | '/newUserGuide/guides/aboutGem'
    | '/newUserGuide/guides/aboutLegendary'
    | '/newUserGuide/guides/getCoin'
    | '/newUserGuide/guides/recommendCookie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/login'
    | '/auth/signup'
    | '/board/$articleId'
    | '/board/write'
    | '/cookie/$articleId'
    | '/management/banner'
    | '/management/board'
    | '/management/cookieMan'
    | '/management/inquiry'
    | '/management/petMan'
    | '/management/treasure'
    | '/newUserGuide/list'
    | '/strategy/cookietier'
    | '/board'
    | '/cookie'
    | '/management'
    | '/management/cookie/add'
    | '/management/pet/add'
    | '/newUserGuide/guides/aboutBox'
    | '/newUserGuide/guides/aboutCrystal'
    | '/newUserGuide/guides/aboutGem'
    | '/newUserGuide/guides/aboutLegendary'
    | '/newUserGuide/guides/getCoin'
    | '/newUserGuide/guides/recommendCookie'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth/login'
    | '/auth/signup'
    | '/board/$articleId'
    | '/board/write'
    | '/cookie/$articleId'
    | '/management/banner'
    | '/management/board'
    | '/management/cookieMan'
    | '/management/inquiry'
    | '/management/petMan'
    | '/management/treasure'
    | '/newUserGuide/list'
    | '/strategy/cookietier'
    | '/board/'
    | '/cookie/'
    | '/management/'
    | '/management/cookie/add'
    | '/management/pet/add'
    | '/newUserGuide/guides/aboutBox'
    | '/newUserGuide/guides/aboutCrystal'
    | '/newUserGuide/guides/aboutGem'
    | '/newUserGuide/guides/aboutLegendary'
    | '/newUserGuide/guides/getCoin'
    | '/newUserGuide/guides/recommendCookie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BoardArticleIdRoute: typeof BoardArticleIdRoute
  BoardWriteRoute: typeof BoardWriteRoute
  CookieArticleIdRoute: typeof CookieArticleIdRoute
  ManagementBannerRoute: typeof ManagementBannerRoute
  ManagementBoardRoute: typeof ManagementBoardRoute
  ManagementCookieManRoute: typeof ManagementCookieManRoute
  ManagementInquiryRoute: typeof ManagementInquiryRoute
  ManagementPetManRoute: typeof ManagementPetManRoute
  ManagementTreasureRoute: typeof ManagementTreasureRoute
  NewUserGuideListRoute: typeof NewUserGuideListRoute
  StrategyCookietierRoute: typeof StrategyCookietierRoute
  BoardIndexRoute: typeof BoardIndexRoute
  CookieIndexRoute: typeof CookieIndexRoute
  ManagementIndexRoute: typeof ManagementIndexRoute
  ManagementCookieAddRoute: typeof ManagementCookieAddRoute
  ManagementPetAddRoute: typeof ManagementPetAddRoute
  NewUserGuideGuidesAboutBoxRoute: typeof NewUserGuideGuidesAboutBoxRoute
  NewUserGuideGuidesAboutCrystalRoute: typeof NewUserGuideGuidesAboutCrystalRoute
  NewUserGuideGuidesAboutGemRoute: typeof NewUserGuideGuidesAboutGemRoute
  NewUserGuideGuidesAboutLegendaryRoute: typeof NewUserGuideGuidesAboutLegendaryRoute
  NewUserGuideGuidesGetCoinRoute: typeof NewUserGuideGuidesGetCoinRoute
  NewUserGuideGuidesRecommendCookieRoute: typeof NewUserGuideGuidesRecommendCookieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/': {
      id: '/management/'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie/': {
      id: '/cookie/'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/': {
      id: '/board/'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy/cookietier': {
      id: '/strategy/cookietier'
      path: '/strategy/cookietier'
      fullPath: '/strategy/cookietier'
      preLoaderRoute: typeof StrategyCookietierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newUserGuide/list': {
      id: '/newUserGuide/list'
      path: '/newUserGuide/list'
      fullPath: '/newUserGuide/list'
      preLoaderRoute: typeof NewUserGuideListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/treasure': {
      id: '/management/treasure'
      path: '/management/treasure'
      fullPath: '/management/treasure'
      preLoaderRoute: typeof ManagementTreasureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/petMan': {
      id: '/management/petMan'
      path: '/management/petMan'
      fullPath: '/management/petMan'
      preLoaderRoute: typeof ManagementPetManRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/inquiry': {
      id: '/management/inquiry'
      path: '/management/inquiry'
      fullPath: '/management/inquiry'
      preLoaderRoute: typeof ManagementInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/cookieMan': {
      id: '/management/cookieMan'
      path: '/management/cookieMan'
      fullPath: '/management/cookieMan'
      preLoaderRoute: typeof ManagementCookieManRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/board': {
      id: '/management/board'
      path: '/management/board'
      fullPath: '/management/board'
      preLoaderRoute: typeof ManagementBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/banner': {
      id: '/management/banner'
      path: '/management/banner'
      fullPath: '/management/banner'
      preLoaderRoute: typeof ManagementBannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie/$articleId': {
      id: '/cookie/$articleId'
      path: '/cookie/$articleId'
      fullPath: '/cookie/$articleId'
      preLoaderRoute: typeof CookieArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/write': {
      id: '/board/write'
      path: '/board/write'
      fullPath: '/board/write'
      preLoaderRoute: typeof BoardWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$articleId': {
      id: '/board/$articleId'
      path: '/board/$articleId'
      fullPath: '/board/$articleId'
      preLoaderRoute: typeof BoardArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newUserGuide/guides/recommendCookie': {
      id: '/newUserGuide/guides/recommendCookie'
      path: '/newUserGuide/guides/recommendCookie'
      fullPath: '/newUserGuide/guides/recommendCookie'
      preLoaderRoute: typeof NewUserGuideGuidesRecommendCookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newUserGuide/guides/getCoin': {
      id: '/newUserGuide/guides/getCoin'
      path: '/newUserGuide/guides/getCoin'
      fullPath: '/newUserGuide/guides/getCoin'
      preLoaderRoute: typeof NewUserGuideGuidesGetCoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newUserGuide/guides/aboutLegendary': {
      id: '/newUserGuide/guides/aboutLegendary'
      path: '/newUserGuide/guides/aboutLegendary'
      fullPath: '/newUserGuide/guides/aboutLegendary'
      preLoaderRoute: typeof NewUserGuideGuidesAboutLegendaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newUserGuide/guides/aboutGem': {
      id: '/newUserGuide/guides/aboutGem'
      path: '/newUserGuide/guides/aboutGem'
      fullPath: '/newUserGuide/guides/aboutGem'
      preLoaderRoute: typeof NewUserGuideGuidesAboutGemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newUserGuide/guides/aboutCrystal': {
      id: '/newUserGuide/guides/aboutCrystal'
      path: '/newUserGuide/guides/aboutCrystal'
      fullPath: '/newUserGuide/guides/aboutCrystal'
      preLoaderRoute: typeof NewUserGuideGuidesAboutCrystalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newUserGuide/guides/aboutBox': {
      id: '/newUserGuide/guides/aboutBox'
      path: '/newUserGuide/guides/aboutBox'
      fullPath: '/newUserGuide/guides/aboutBox'
      preLoaderRoute: typeof NewUserGuideGuidesAboutBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/pet/add': {
      id: '/management/pet/add'
      path: '/management/pet/add'
      fullPath: '/management/pet/add'
      preLoaderRoute: typeof ManagementPetAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/cookie/add': {
      id: '/management/cookie/add'
      path: '/management/cookie/add'
      fullPath: '/management/cookie/add'
      preLoaderRoute: typeof ManagementCookieAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  BoardArticleIdRoute: BoardArticleIdRoute,
  BoardWriteRoute: BoardWriteRoute,
  CookieArticleIdRoute: CookieArticleIdRoute,
  ManagementBannerRoute: ManagementBannerRoute,
  ManagementBoardRoute: ManagementBoardRoute,
  ManagementCookieManRoute: ManagementCookieManRoute,
  ManagementInquiryRoute: ManagementInquiryRoute,
  ManagementPetManRoute: ManagementPetManRoute,
  ManagementTreasureRoute: ManagementTreasureRoute,
  NewUserGuideListRoute: NewUserGuideListRoute,
  StrategyCookietierRoute: StrategyCookietierRoute,
  BoardIndexRoute: BoardIndexRoute,
  CookieIndexRoute: CookieIndexRoute,
  ManagementIndexRoute: ManagementIndexRoute,
  ManagementCookieAddRoute: ManagementCookieAddRoute,
  ManagementPetAddRoute: ManagementPetAddRoute,
  NewUserGuideGuidesAboutBoxRoute: NewUserGuideGuidesAboutBoxRoute,
  NewUserGuideGuidesAboutCrystalRoute: NewUserGuideGuidesAboutCrystalRoute,
  NewUserGuideGuidesAboutGemRoute: NewUserGuideGuidesAboutGemRoute,
  NewUserGuideGuidesAboutLegendaryRoute: NewUserGuideGuidesAboutLegendaryRoute,
  NewUserGuideGuidesGetCoinRoute: NewUserGuideGuidesGetCoinRoute,
  NewUserGuideGuidesRecommendCookieRoute:
    NewUserGuideGuidesRecommendCookieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
